app:
  id: health-order1
apollo:
  meta: http://192.168.1.184:8080
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true
  cache-dir: ~/opt/data

spring:
  redis:
    host: ${redis.host}
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池的最小空闲连接
        min-idle: 0
        # 连接池的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间
        max-wait: 30000
        # 连接超时时间
        timeout: 30000
